/* ===== core/radar.js ===== */
(function(){
  'use strict';
  var PROFILE_PREFIX='radar_profile__',SOCIAL_SNAPSHOT_PREFIX='radar_social_v2__',GITHUB_REPO_PREFIX='radar_github_repo__';
  var DAY_MS=86400000,WEEK_MS=7*DAY_MS,WINDOW_MS=DAY_MS,KEEP_MS=30*DAY_MS;
  function context(){return window.IndustryStore&&IndustryStore.getCurrent?IndustryStore.getCurrent():{id:window.CURRENT_INDUSTRY||'unknown',name:'当前行业'};}
  function key(prefix,id){return prefix+encodeURIComponent(id);}
  function day(time){return new Date(time==null?Date.now():time).toISOString().slice(0,10);}
  function terms(ctx){var cfg=window.DOMAIN_CONFIG||{};return [ctx.name,cfg.name,cfg.display_name].concat(cfg.collect_keywords||[],cfg.keywords||[]).filter(Boolean);}
  function infer(ctx){var list=terms(ctx),source=list.join(' '),developer=/AI|人工智能|大模型|LLM|Agent|编程|开发|代码|软件|开源|机器学习|MCP/i.test(source);return {industryId:ctx.id,industryName:ctx.name||source||'当前行业',type:developer?'developer':'general',sources:{social:{enabled:true,keywords:list.slice(0,12)},github:{enabled:developer,queries:developer?['AI agent','agent framework','AI skill','MCP','LLM agent','developer AI tools']:[]}},updatedAt:new Date().toISOString()};}
  var service={get:function(id){return StorageAdapter.getJSON(key(PROFILE_PREFIX,id),null);},getCurrent:function(){var ctx=context(),profile=this.get(ctx.id);if(!profile||!profile.sources){profile=infer(ctx);this.save(profile);}return profile;},save:function(profile){StorageAdapter.setJSON(key(PROFILE_PREFIX,profile.industryId),profile);return profile;},ensure:function(record){if(!record||!record.id)return null;return this.get(record.id)||this.save(infer(record));}};

  function socialSnapshotKey(id){return key(SOCIAL_SNAPSHOT_PREFIX,id);}
  function socialSnapshots(id){return (StorageAdapter.getJSON(socialSnapshotKey(id),[])||[]).filter(function(item){return item&&item.schemaVersion===2&&Array.isArray(item.items);});}
  function saveSocialSnapshot(id,items,nowMs){var now=nowMs==null?Date.now():nowMs,list=socialSnapshots(id),entry={schemaVersion:2,timestamp:new Date(now).toISOString(),date:day(now),source:'social',items:items},index=list.findIndex(function(item){return item.date===entry.date;});if(index>=0)list[index]=entry;else list.push(entry);list=list.filter(function(item){return now-new Date(item.timestamp||item.date).getTime()<=KEEP_MS;}).sort(function(a,b){return new Date(a.timestamp)-new Date(b.timestamp);});StorageAdapter.setJSON(socialSnapshotKey(id),list);return list;}
  function previousSocial(list){return list.length>1?list[list.length-2]:null;}

  function repoSnapshotKey(industryId,repoId){return GITHUB_REPO_PREFIX+encodeURIComponent(industryId)+'__'+encodeURIComponent(String(repoId));}
  function getRepoSnapshots(industryId,repoId){return StorageAdapter.getJSON(repoSnapshotKey(industryId,repoId),[])||[];}
  function saveRepoSnapshot(industryId,repo,nowMs){var now=nowMs==null?Date.now():nowMs,list=getRepoSnapshots(industryId,repo.id),entry={repoId:String(repo.id),fullName:repo.name||repo.full_name||'',stars:Number(repo.stars!=null?repo.stars:repo.stargazers_count)||0,forks:Number(repo.forks!=null?repo.forks:repo.forks_count)||0,timestamp:new Date(now).toISOString()},today=day(now),index=list.findIndex(function(item){return day(new Date(item.timestamp).getTime())===today;});if(index>=0)list[index]=entry;else list.push(entry);list=list.filter(function(item){return now-new Date(item.timestamp).getTime()<=KEEP_MS;}).sort(function(a,b){return new Date(a.timestamp)-new Date(b.timestamp);});StorageAdapter.setJSON(repoSnapshotKey(industryId,repo.id),list);return list;}
  function closestWeekSnapshot(list,nowMs){var target=nowMs-WEEK_MS,best=null,distance=Infinity;list.forEach(function(item){var delta=Math.abs(new Date(item.timestamp).getTime()-target);if(delta<=WINDOW_MS&&delta<distance){best=item;distance=delta;}});return best;}
  function githubMetrics(industryId,repo,nowMs){var now=nowMs==null?Date.now():nowMs,created=new Date(repo.createdAt||repo.created_at).getTime(),isNew=isFinite(created)&&now-created<WEEK_MS,currentStars=Number(repo.stars!=null?repo.stars:repo.stargazers_count)||0,old=isNew?null:closestWeekSnapshot(getRepoSnapshots(industryId,repo.id),now),result={historyStatus:'insufficient',isNew:isNew,ageDays:isFinite(created)?Math.max(0,Math.floor((now-created)/DAY_MS)):null,starsGained7d:null,growthRate7d:null};if(!isNew&&old){result.historyStatus='sufficient';result.starsGained7d=currentStars-Number(old.stars||0);result.growthRate7d=old.stars>0?result.starsGained7d/old.stars:null;}return result;}
  function rankWeekly(items){return items.filter(function(repo){return !repo.isNew&&repo.historyStatus==='sufficient';}).sort(function(a,b){return (b.starsGained7d-a.starsGained7d)||((b.growthRate7d||0)-(a.growthRate7d||0));});}
  function normalizeRepo(repo){return {id:String(repo.id),name:repo.full_name,owner:repo.owner&&repo.owner.login||'',url:repo.html_url,description:repo.description||'',topics:repo.topics||[],language:repo.language||'',stars:repo.stargazers_count||0,forks:repo.forks_count||0,updatedAt:repo.updated_at,createdAt:repo.created_at};}
  function githubSearch(query,since){return fetch('https://api.github.com/search/repositories?q='+encodeURIComponent(query+' stars:>10 pushed:>='+since)+'&sort=stars&order=desc&per_page=20',{headers:{Accept:'application/vnd.github+json'}}).then(function(response){if(!response.ok)throw new Error(response.status===403?'GitHub 公共接口额度暂时用尽。':'GitHub 数据加载失败。');return response.json();}).then(function(body){return body.items||[];});}
  var githubLoads={};
  var GitHubRadarAdapter={load:function(profile){var loadKey=profile.industryId+'__'+day();if(githubLoads[loadKey])return githubLoads[loadKey];var now=Date.now(),activeSince=day(now-WEEK_MS),queries=profile.sources.github.queries||[];githubLoads[loadKey]=Promise.all(queries.map(function(query){return githubSearch(query,activeSince).then(function(value){return {ok:true,value:value};},function(){return {ok:false,value:[]};});})).then(function(results){var groups=results.filter(function(result){return result.ok;}).map(function(result){return result.value;});if(!groups.length)throw new Error('GitHub 公共接口额度暂时用尽。');var seen={},repos=[];groups.forEach(function(group){group.forEach(function(repo){if(!seen[repo.id]){seen[repo.id]=true;repos.push(repo);}});});var items=repos.map(normalizeRepo).map(function(repo){var metrics=githubMetrics(profile.industryId,repo,now);saveRepoSnapshot(profile.industryId,repo,now);Object.keys(metrics).forEach(function(name){repo[name]=metrics[name];});return repo;});var weekly=rankWeekly(items).slice(0,20);var emerging=items.filter(function(repo){return repo.isNew;}).sort(function(a,b){return b.stars-a.stars;}).slice(0,20);var accumulating=items.filter(function(repo){return !repo.isNew&&repo.historyStatus==='insufficient';}).sort(function(a,b){return b.stars-a.stars;}).slice(0,20);return {kind:'github',title:'GitHub Radar',items:weekly.concat(emerging),weekly:weekly,emerging:emerging,accumulating:accumulating,note:'来源：GitHub 官方公开 API；周增长只使用最接近七天前（允许 ±24 小时）的真实快照差值。'};}).catch(function(error){delete githubLoads[loadKey];throw error;});return githubLoads[loadKey];}};

  function workIdentity(work,index){var stable=work&&(work.workId||work.sourceId||work.noteId);if(stable)return String(stable);var fallback=[work&&work.platform,work&&(work.workUrl||work.url),work&&work.title,work&&(work.accountName||work.author),work&&work.publishTime].filter(Boolean).join('|');return fallback||('row:'+index);}
  function metric(work,name,aliases){var value=work&&work[name];if(value==null){for(var i=0;i<aliases.length;i++){if(work&&work[aliases[i]]!=null){value=work[aliases[i]];break;}}}value=Number(value);return isFinite(value)&&value>0?value:0;}
  function aggregateSocial(data){var works=Array.isArray(data&&data.works)?data.works:[],hotwords=Array.isArray(data&&data.hotwords)?data.hotwords:[],searchTotals={},keywordOrder=[];hotwords.forEach(function(item){var name=String(item&&item.keyword||'').trim();if(!name)return;if(searchTotals[name]==null){searchTotals[name]=0;keywordOrder.push(name);}searchTotals[name]+=metric(item,'total',[]);});var groups={};works.forEach(function(work,index){var keyword=String(work&&(work._keyword||work.keyword)||'').trim();if(!keyword)return;if(!groups[keyword])groups[keyword]={seen:{},works:[]};var id=workIdentity(work,index);if(groups[keyword].seen[id])return;groups[keyword].seen[id]=true;groups[keyword].works.push(work);});var contractErrors=[];var items=keywordOrder.map(function(keyword){var sample=groups[keyword]?groups[keyword].works:[],item={id:keyword,keyword:keyword,name:keyword,sampleWorks:sample.length,likes:0,collects:0,comments:0,shares:0,maxLike:0,searchTotal:searchTotals[keyword],trend:'当前样本'};sample.forEach(function(work){var likes=metric(work,'likeCount',['likes','workLikedCount']),collects=metric(work,'collectCount',['collects','favoriteCount']),comments=metric(work,'commentCount',['comments']),shares=metric(work,'shareCount',['shares','repostCount']);item.likes+=likes;item.collects+=collects;item.comments+=comments;item.shares+=shares;if(likes>item.maxLike)item.maxLike=likes;});if(item.sampleWorks>works.length)contractErrors.push({keyword:keyword,sampleWorks:item.sampleWorks,worksLength:works.length});return item;});return {items:items,contractErrors:contractErrors,worksLength:works.length};}
  function engagement(item){return Number(item.likes||0)+Number(item.collects||0)*2+Number(item.comments||0)*2+Number(item.shares||0)*3;}
  function applySocialTrend(items,old){if(!old)return items;var oldMap={};old.items.forEach(function(item){oldMap[item.id]=item;});items.forEach(function(item){var before=oldMap[item.id];if(!before){item.trend='数据不足';return;}item.sampleWorksDelta=item.sampleWorks-Number(before.sampleWorks||0);item.likesDelta=item.likes-Number(before.likes||0);item.collectsDelta=item.collects-Number(before.collects||0);item.commentsDelta=item.comments-Number(before.comments||0);item.sharesDelta=item.shares-Number(before.shares||0);var oldEngagement=engagement(before),currentEngagement=engagement(item);item.engagementDelta=currentEngagement-oldEngagement;item.engagementDeltaRate=oldEngagement>0?item.engagementDelta/oldEngagement:null;if(item.engagementDeltaRate==null)item.trend='数据不足';else if(item.engagementDeltaRate>=0.25)item.trend='快速升温';else if(item.engagementDeltaRate>0)item.trend='升温';else if(item.engagementDeltaRate<0)item.trend='降温';else item.trend='稳定';});return items;}
  var SocialRadarAdapter={load:function(profile,data){var aggregate=aggregateSocial(data||{}),items=aggregate.items.sort(function(a,b){return (engagement(b)-engagement(a))||(b.sampleWorks-a.sampleWorks)||(b.searchTotal-a.searchTotal);}).slice(0,20),snapshotItems=items.map(function(item){return {id:item.id,sampleWorks:item.sampleWorks,likes:item.likes,collects:item.collects,comments:item.comments,shares:item.shares,maxLike:item.maxLike,searchTotal:item.searchTotal};}),list=saveSocialSnapshot(profile.industryId,snapshotItems),old=previousSocial(list);applySocialTrend(items,old);if(aggregate.contractErrors.length&&window.console&&console.error)console.error('[DATA_CONTRACT_ERROR]',aggregate.contractErrors);return Promise.resolve({kind:'social',title:'行业本周升温关键词',items:items,contractErrors:aggregate.contractErrors,note:old?'趋势基于当前行业两个最近 Social Radar v2 真实采集快照；样本作品变化与互动变化分开计算。':'当前只有一个 Social Radar v2 真实采集快照，仅显示当前样本；继续采集后生成趋势。'});}};
  SocialRadarAdapter._test={socialSnapshotKey:socialSnapshotKey,socialSnapshots:socialSnapshots,saveSocialSnapshot:saveSocialSnapshot,aggregateSocial:aggregateSocial,engagement:engagement,applySocialTrend:applySocialTrend,workIdentity:workIdentity};
  GitHubRadarAdapter._test={repoSnapshotKey:repoSnapshotKey,getRepoSnapshots:getRepoSnapshots,saveRepoSnapshot:saveRepoSnapshot,closestWeekSnapshot:closestWeekSnapshot,githubMetrics:githubMetrics,rankWeekly:rankWeekly,normalizeRepo:normalizeRepo};
  window.RadarProfileService=service;
  window.RadarAdapters={github:GitHubRadarAdapter,social:SocialRadarAdapter};
})();
