/* ===== core/radar.js ===== */
(function(){
  'use strict';
  var PROFILE_PREFIX='radar_profile__',SNAPSHOT_PREFIX='radar_snapshots__',GITHUB_REPO_PREFIX='radar_github_repo__';
  var DAY_MS=86400000,WEEK_MS=7*DAY_MS,WINDOW_MS=DAY_MS,KEEP_MS=30*DAY_MS;
  function context(){return window.IndustryStore&&IndustryStore.getCurrent?IndustryStore.getCurrent():{id:window.CURRENT_INDUSTRY||'unknown',name:'当前行业'};}
  function key(prefix,id){return prefix+encodeURIComponent(id);}
  function day(time){return new Date(time==null?Date.now():time).toISOString().slice(0,10);}
  function terms(ctx){var cfg=window.DOMAIN_CONFIG||{};return [ctx.name,cfg.name,cfg.display_name].concat(cfg.collect_keywords||[],cfg.keywords||[]).filter(Boolean);}
  function infer(ctx){var list=terms(ctx),source=list.join(' '),developer=/AI|人工智能|大模型|LLM|Agent|编程|开发|代码|软件|开源|机器学习|MCP/i.test(source);return {industryId:ctx.id,industryName:ctx.name||source||'当前行业',type:developer?'developer':'general',sources:{social:{enabled:true,keywords:list.slice(0,12)},github:{enabled:developer,queries:developer?['AI agent','agent framework','AI skill','MCP','LLM agent','developer AI tools']:[]}},updatedAt:new Date().toISOString()};}
  var service={get:function(id){return StorageAdapter.getJSON(key(PROFILE_PREFIX,id),null);},getCurrent:function(){var ctx=context(),profile=this.get(ctx.id);if(!profile||!profile.sources){profile=infer(ctx);this.save(profile);}return profile;},save:function(profile){StorageAdapter.setJSON(key(PROFILE_PREFIX,profile.industryId),profile);return profile;},ensure:function(record){if(!record||!record.id)return null;return this.get(record.id)||this.save(infer(record));}};

  function snapshots(id){return StorageAdapter.getJSON(key(SNAPSHOT_PREFIX,id),[])||[];}
  function saveSnapshot(id,source,items){var now=Date.now(),list=snapshots(id),entry={timestamp:new Date(now).toISOString(),date:day(now),source:source,items:items},index=list.findIndex(function(item){return item.date===entry.date&&item.source===source;});if(index>=0)list[index]=entry;else list.push(entry);list=list.filter(function(item){return now-new Date(item.timestamp||item.date).getTime()<=KEEP_MS;});StorageAdapter.setJSON(key(SNAPSHOT_PREFIX,id),list);return list;}
  function previous(list,source){var same=list.filter(function(item){return item.source===source;});return same.length>1?same[same.length-2]:null;}

  function repoSnapshotKey(industryId,repoId){return GITHUB_REPO_PREFIX+encodeURIComponent(industryId)+'__'+encodeURIComponent(String(repoId));}
  function getRepoSnapshots(industryId,repoId){return StorageAdapter.getJSON(repoSnapshotKey(industryId,repoId),[])||[];}
  function saveRepoSnapshot(industryId,repo,nowMs){var now=nowMs==null?Date.now():nowMs,list=getRepoSnapshots(industryId,repo.id),entry={repoId:String(repo.id),fullName:repo.name||repo.full_name||'',stars:Number(repo.stars!=null?repo.stars:repo.stargazers_count)||0,forks:Number(repo.forks!=null?repo.forks:repo.forks_count)||0,timestamp:new Date(now).toISOString()},today=day(now),index=list.findIndex(function(item){return day(new Date(item.timestamp).getTime())===today;});if(index>=0)list[index]=entry;else list.push(entry);list=list.filter(function(item){return now-new Date(item.timestamp).getTime()<=KEEP_MS;}).sort(function(a,b){return new Date(a.timestamp)-new Date(b.timestamp);});StorageAdapter.setJSON(repoSnapshotKey(industryId,repo.id),list);return list;}
  function closestWeekSnapshot(list,nowMs){var target=nowMs-WEEK_MS,best=null,distance=Infinity;list.forEach(function(item){var delta=Math.abs(new Date(item.timestamp).getTime()-target);if(delta<=WINDOW_MS&&delta<distance){best=item;distance=delta;}});return best;}
  function githubMetrics(industryId,repo,nowMs){var now=nowMs==null?Date.now():nowMs,created=new Date(repo.createdAt||repo.created_at).getTime(),isNew=isFinite(created)&&now-created<WEEK_MS,currentStars=Number(repo.stars!=null?repo.stars:repo.stargazers_count)||0,old=isNew?null:closestWeekSnapshot(getRepoSnapshots(industryId,repo.id),now),result={historyStatus:'insufficient',isNew:isNew,ageDays:isFinite(created)?Math.max(0,Math.floor((now-created)/DAY_MS)):null,starsGained7d:null,growthRate7d:null};if(!isNew&&old){result.historyStatus='sufficient';result.starsGained7d=currentStars-Number(old.stars||0);result.growthRate7d=old.stars>0?result.starsGained7d/old.stars:null;}return result;}
  function rankWeekly(items){return items.filter(function(repo){return !repo.isNew&&repo.historyStatus==='sufficient';}).sort(function(a,b){return (b.starsGained7d-a.starsGained7d)||((b.growthRate7d||0)-(a.growthRate7d||0));});}
  function normalizeRepo(repo){return {id:String(repo.id),name:repo.full_name,owner:repo.owner&&repo.owner.login||'',url:repo.html_url,description:repo.description||'',topics:repo.topics||[],language:repo.language||'',stars:repo.stargazers_count||0,forks:repo.forks_count||0,updatedAt:repo.updated_at,createdAt:repo.created_at};}
  function githubSearch(query,since){return fetch('https://api.github.com/search/repositories?q='+encodeURIComponent(query+' stars:>10 pushed:>='+since)+'&sort=stars&order=desc&per_page=20',{headers:{Accept:'application/vnd.github+json'}}).then(function(response){if(!response.ok)throw new Error(response.status===403?'GitHub 公共接口额度暂时用尽。':'GitHub 数据加载失败。');return response.json();}).then(function(body){return body.items||[];});}
  var githubLoads={};
  var GitHubRadarAdapter={load:function(profile){var loadKey=profile.industryId+'__'+day();if(githubLoads[loadKey])return githubLoads[loadKey];var now=Date.now(),activeSince=day(now-WEEK_MS),queries=profile.sources.github.queries||[];githubLoads[loadKey]=Promise.all(queries.map(function(query){return githubSearch(query,activeSince).then(function(value){return {ok:true,value:value};},function(){return {ok:false,value:[]};});})).then(function(results){var groups=results.filter(function(result){return result.ok;}).map(function(result){return result.value;});if(!groups.length)throw new Error('GitHub 公共接口额度暂时用尽。');var seen={},repos=[];groups.forEach(function(group){group.forEach(function(repo){if(!seen[repo.id]){seen[repo.id]=true;repos.push(repo);}});});var items=repos.map(normalizeRepo).map(function(repo){var metrics=githubMetrics(profile.industryId,repo,now);saveRepoSnapshot(profile.industryId,repo,now);Object.keys(metrics).forEach(function(name){repo[name]=metrics[name];});return repo;});var weekly=rankWeekly(items).slice(0,20);var emerging=items.filter(function(repo){return repo.isNew;}).sort(function(a,b){return b.stars-a.stars;}).slice(0,20);var accumulating=items.filter(function(repo){return !repo.isNew&&repo.historyStatus==='insufficient';}).sort(function(a,b){return b.stars-a.stars;}).slice(0,20);return {kind:'github',title:'GitHub Radar',items:weekly.concat(emerging),weekly:weekly,emerging:emerging,accumulating:accumulating,note:'来源：GitHub 官方公开 API；周增长只使用最接近七天前（允许 ±24 小时）的真实快照差值。'};}).catch(function(error){delete githubLoads[loadKey];throw error;});return githubLoads[loadKey];}};

  var SocialRadarAdapter={load:function(profile,data){var items=(data.hotwords||[]).map(function(item){return {id:item.keyword,name:item.keyword,works:Number(item.total||0),likes:Number(item.total_likes||item.likes||0),collects:Number(item.total_collects||item.collects||0),comments:Number(item.total_comments||item.comments||0),shares:Number(item.total_shares||item.shares||0),maxLike:Number(item.max_like||0),trend:'当前热门'};}).filter(function(item){return item.name;}).sort(function(a,b){return (b.maxLike+b.works)-(a.maxLike+a.works);}).slice(0,20),list=saveSnapshot(profile.industryId,'social',items.map(function(item){return {id:item.id,works:item.works,likes:item.likes,collects:item.collects,comments:item.comments,shares:item.shares,maxLike:item.maxLike};})),old=previous(list,'social');if(old){var oldMap={};old.items.forEach(function(item){oldMap[item.id]=item;});items.forEach(function(item){var before=oldMap[item.id],delta=before?(item.works-before.works)+(item.likes-before.likes):0;if(!before)item.trend='数据不足';else if(delta>100)item.trend='快速升温';else if(delta>0)item.trend='升温';else if(delta<0)item.trend='降温';else item.trend='稳定';});}return Promise.resolve({kind:'social',title:'行业本周升温关键词',items:items,note:old?'趋势基于当前行业两个最近真实采集快照的指标差值。':'当前只有一个真实采集快照，暂不判断上涨或爆发；继续采集后生成趋势。'});}};
  GitHubRadarAdapter._test={repoSnapshotKey:repoSnapshotKey,getRepoSnapshots:getRepoSnapshots,saveRepoSnapshot:saveRepoSnapshot,closestWeekSnapshot:closestWeekSnapshot,githubMetrics:githubMetrics,rankWeekly:rankWeekly,normalizeRepo:normalizeRepo};
  window.RadarProfileService=service;
  window.RadarAdapters={github:GitHubRadarAdapter,social:SocialRadarAdapter};
})();
