/* ===== core/radar.js ===== */
(function(){
  'use strict';
  var PROFILE_PREFIX='radar_profile__',SNAPSHOT_PREFIX='radar_snapshots__';
  function context(){return window.IndustryStore&&IndustryStore.getCurrent?IndustryStore.getCurrent():{id:window.CURRENT_INDUSTRY||'unknown',name:'当前行业'};}
  function key(prefix,id){return prefix+encodeURIComponent(id);}
  function day(){return new Date().toISOString().slice(0,10);}
  function terms(ctx){var cfg=window.DOMAIN_CONFIG||{};return [ctx.name,cfg.name,cfg.display_name].concat(cfg.collect_keywords||[],cfg.keywords||[]).filter(Boolean);}
  function infer(ctx){var list=terms(ctx),source=list.join(' '),developer=/AI|人工智能|大模型|LLM|Agent|编程|开发|代码|软件|开源|机器学习|MCP/i.test(source);return {industryId:ctx.id,industryName:ctx.name||source||'当前行业',type:developer?'developer':'general',sources:{social:{enabled:true,keywords:list.slice(0,12)},github:{enabled:developer,queries:developer?['AI agent','agent framework','AI skill','MCP','LLM agent']:[]}},updatedAt:new Date().toISOString()};}
  var service={get:function(id){return StorageAdapter.getJSON(key(PROFILE_PREFIX,id),null);},getCurrent:function(){var ctx=context(),profile=this.get(ctx.id);if(!profile||!profile.sources){profile=infer(ctx);this.save(profile);}return profile;},save:function(profile){StorageAdapter.setJSON(key(PROFILE_PREFIX,profile.industryId),profile);return profile;},ensure:function(record){if(!record||!record.id)return null;return this.get(record.id)||this.save(infer(record));}};
  function snapshots(id){return StorageAdapter.getJSON(key(SNAPSHOT_PREFIX,id),[])||[];}
  function saveSnapshot(id,source,items){var list=snapshots(id),entry={timestamp:new Date().toISOString(),date:day(),source:source,items:items},index=list.findIndex(function(item){return item.date===entry.date&&item.source===source;});if(index>=0)list[index]=entry;else list.push(entry);list=list.slice(-60);StorageAdapter.setJSON(key(SNAPSHOT_PREFIX,id),list);return list;}
  function previous(list,source){var same=list.filter(function(item){return item.source===source;});return same.length>1?same[same.length-2]:null;}
  function githubSearch(query,since){return fetch('https://api.github.com/search/repositories?q='+encodeURIComponent(query+' created:>='+since)+'&sort=stars&order=desc&per_page=20',{headers:{Accept:'application/vnd.github+json'}}).then(function(response){if(!response.ok)throw new Error(response.status===403?'GitHub 公共接口额度暂时用尽。':'GitHub 数据加载失败。');return response.json();}).then(function(body){return body.items||[];});}
  var GitHubRadarAdapter={load:function(profile){var since=new Date(Date.now()-7*86400000).toISOString().slice(0,10),queries=profile.sources.github.queries||[];return Promise.all(queries.map(function(query){return githubSearch(query,since);})).then(function(groups){var seen={},repos=[];groups.forEach(function(group){group.forEach(function(repo){if(!seen[repo.id]){seen[repo.id]=true;repos.push(repo);}});});var items=repos.map(function(repo){return {id:String(repo.id),name:repo.full_name,owner:repo.owner&&repo.owner.login||'',url:repo.html_url,description:repo.description||'',topics:repo.topics||[],language:repo.language||'',stars:repo.stargazers_count||0,starsGained7d:repo.stargazers_count||0,growthRate7d:null,forks:repo.forks_count||0,updatedAt:repo.updated_at,createdAt:repo.created_at};}).sort(function(a,b){return b.starsGained7d-a.starsGained7d;}).slice(0,20);saveSnapshot(profile.industryId,'github',items.map(function(item){return {id:item.id,stars:item.stars};}));return {kind:'github',title:'GitHub 本周上升项目',items:items,note:'来源：GitHub 官方公开 API。仅纳入最近 7 天创建的相关仓库，因此 +Stars 表示项目创建以来且不超过 7 天的累计增量；成熟仓库需后续快照差值。'};});}};
  var SocialRadarAdapter={load:function(profile,data){var items=(data.hotwords||[]).map(function(item){return {id:item.keyword,name:item.keyword,works:Number(item.total||0),likes:Number(item.total_likes||item.likes||0),collects:Number(item.total_collects||item.collects||0),comments:Number(item.total_comments||item.comments||0),shares:Number(item.total_shares||item.shares||0),maxLike:Number(item.max_like||0),trend:'当前热门'};}).filter(function(item){return item.name;}).sort(function(a,b){return (b.maxLike+b.works)-(a.maxLike+a.works);}).slice(0,20),list=saveSnapshot(profile.industryId,'social',items.map(function(item){return {id:item.id,works:item.works,likes:item.likes,collects:item.collects,comments:item.comments,shares:item.shares,maxLike:item.maxLike};})),old=previous(list,'social');if(old){var oldMap={};old.items.forEach(function(item){oldMap[item.id]=item;});items.forEach(function(item){var before=oldMap[item.id],delta=before?(item.works-before.works)+(item.likes-before.likes):0;if(!before)item.trend='数据不足';else if(delta>100)item.trend='快速升温';else if(delta>0)item.trend='升温';else if(delta<0)item.trend='降温';else item.trend='稳定';});}return Promise.resolve({kind:'social',title:'行业本周升温关键词',items:items,note:old?'趋势基于当前行业两个最近真实采集快照的指标差值。':'当前只有一个真实采集快照，暂不判断上涨或爆发；继续采集后生成趋势。'});}};
  window.RadarProfileService=service;
  window.RadarAdapters={github:GitHubRadarAdapter,social:SocialRadarAdapter};
})();
