/* ===== core/textAIProvider.js ===== */
(function(){
  'use strict';
  var STORE_KEY='user_text_ai_configs',LEGACY_KEY='user_text_ai_config',TIMEOUT_MS=40000;
  var PRESETS={
    openai:{id:'openai',name:'OpenAI',baseUrl:'https://api.openai.com/v1',authType:'bearer',adapter:'openai-compatible',recommendedModels:['gpt-5.4','gpt-5.4-mini','gpt-5.4-nano'],apiKeyGuideUrl:'https://platform.openai.com/api-keys',homepage:'https://platform.openai.com/',supportsDirectBrowser:true},
    claude:{id:'claude',name:'Claude',baseUrl:'https://api.anthropic.com/v1',authType:'x-api-key',adapter:'anthropic',recommendedModels:['claude-sonnet-4-6','claude-opus-4-6','claude-haiku-4-5'],apiKeyGuideUrl:'https://console.anthropic.com/settings/keys',homepage:'https://console.anthropic.com/',supportsDirectBrowser:true},
    gemini:{id:'gemini',name:'Gemini',baseUrl:'https://generativelanguage.googleapis.com/v1beta',authType:'x-goog-api-key',adapter:'gemini',recommendedModels:['gemini-3.8-flash','gemini-3.5-flash','gemini-3.5-pro'],apiKeyGuideUrl:'https://aistudio.google.com/app/apikey',homepage:'https://aistudio.google.com/',supportsDirectBrowser:true},
    deepseek:{id:'deepseek',name:'DeepSeek',baseUrl:'https://api.deepseek.com',authType:'bearer',adapter:'openai-compatible',recommendedModels:['deepseek-chat','deepseek-reasoner'],apiKeyGuideUrl:'https://platform.deepseek.com/api_keys',homepage:'https://platform.deepseek.com/',supportsDirectBrowser:true},
    qwen:{id:'qwen',name:'通义千问',baseUrl:'https://dashscope.aliyuncs.com/compatible-mode/v1',authType:'bearer',adapter:'openai-compatible',recommendedModels:['qwen-plus','qwen-turbo','qwen-max'],apiKeyGuideUrl:'https://bailian.console.aliyun.com/',homepage:'https://bailian.console.aliyun.com/',supportsDirectBrowser:true},
    doubao:{id:'doubao',name:'豆包',baseUrl:'https://ark.cn-beijing.volces.com/api/v3',authType:'bearer',adapter:'openai-compatible',modelLabel:'Model / Endpoint ID',recommendedModels:['doubao-seed-2-1-pro-260915','doubao-seed-2-1-lite-260915','doubao-seed-2-1-turbo-260628'],apiKeyGuideUrl:'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',homepage:'https://console.volcengine.com/ark/',supportsDirectBrowser:true},
    'xiaomi-mimo':{id:'xiaomi-mimo',name:'小米 MiMo',baseUrl:'https://api.xiaomimimo.com/v1',authType:'bearer',adapter:'openai-compatible',recommendedModels:['mimo-v2.5-pro'],apiKeyGuideUrl:'https://platform.xiaomimimo.com/',homepage:'https://platform.xiaomimimo.com/',supportsDirectBrowser:true},
    'openai-compatible':{id:'openai-compatible',name:'OpenAI 兼容服务',baseUrl:'',authType:'bearer',adapter:'openai-compatible',recommendedModels:[],apiKeyGuideUrl:'',homepage:'',supportsDirectBrowser:true,showBaseUrl:true},
    custom:{id:'custom',name:'自定义',baseUrl:'',authType:'bearer',adapter:'openai-compatible',recommendedModels:[],apiKeyGuideUrl:'',homepage:'',supportsDirectBrowser:true,showBaseUrl:true}
  };
  function clean(v){return String(v==null?'':v).trim();} function clone(v){return v?JSON.parse(JSON.stringify(v)):v;}
  function emptyStore(){return {currentProviderId:'openai',providers:{}};}
  function configValue(v,id){v=v||{};id=clean(id||v.providerId||v.provider||'openai');var p=PRESETS[id]||PRESETS.openai;return {providerId:id,providerType:p.adapter,baseUrl:clean(v.baseUrl||p.baseUrl).replace(/\/+$/,''),apiKey:clean(v.apiKey),model:clean(v.model),createdAt:v.createdAt||'',updatedAt:v.updatedAt||'',connection:v.connection&&typeof v.connection==='object'?v.connection:{status:'untested'}};}
  function loadStore(){var s=StorageAdapter.getJSON(STORE_KEY,null);if(s&&s.providers)return s;s=emptyStore();var legacy=StorageAdapter.getJSON(LEGACY_KEY,null);if(legacy&&legacy.apiKey){var id=legacy.providerId||'xiaomi-mimo';s.currentProviderId=id;s.providers[id]=configValue(legacy,id);StorageAdapter.setJSON(STORE_KEY,s);}return s;}
  function saveStore(s){StorageAdapter.setJSON(STORE_KEY,s);return s;} function getConfig(id){var s=loadStore();id=id||s.currentProviderId;return s.providers[id]?configValue(s.providers[id],id):null;} function getCurrentConfig(){var s=loadStore();return getConfig(s.currentProviderId);}
  function selectProvider(id){if(!PRESETS[id])return null;var s=loadStore();s.currentProviderId=id;saveStore(s);return getConfig(id);} function validate(v){var c=configValue(v),m=[];if(!PRESETS[c.providerId])m.push('Provider');if(!c.baseUrl)m.push('API Base URL');if(!c.apiKey)m.push('API Key');if(!c.model)m.push('Model');return {valid:!m.length,missing:m,config:c};}
  function signature(c){c=configValue(c);return [c.providerId,c.baseUrl,c.model,c.apiKey.slice(-8)].join('|');} function saveConfig(v){var x=validate(v);if(!x.valid)return x;var s=loadStore(),old=s.providers[x.config.providerId],now=new Date().toISOString(),c=x.config;c.createdAt=old&&old.createdAt||now;c.updatedAt=now;if(!c.connection||c.connection.signature!==signature(c))c.connection={status:'untested'};s.currentProviderId=c.providerId;s.providers[c.providerId]=c;saveStore(s);return {valid:true,config:clone(c)};}
  function setConnection(r){var s=loadStore(),id=s.currentProviderId,c=s.providers[id];if(!c)return null;c=configValue(c,id);c.connection=Object.assign({status:'untested'},r||{},{signature:signature(c),testedAt:new Date().toISOString()});c.updatedAt=new Date().toISOString();s.providers[id]=c;saveStore(s);return clone(c);} function clearConfig(id){var s=loadStore();id=id||s.currentProviderId;delete s.providers[id];saveStore(s);return true;} function maskKey(k){k=clean(k);return k?'****'+k.slice(-4):'未保存';}
  window.TEXT_PROVIDER_PRESETS=PRESETS;window.PROVIDER_PRESETS=PRESETS;window.TextAIProvider={storeKey:STORE_KEY,getPresets:function(){return clone(PRESETS);},getPreset:function(id){return clone(PRESETS[id]||null);},getCurrentProviderId:function(){return loadStore().currentProviderId;},selectProvider:selectProvider,getConfig:getConfig,getCurrentConfig:getCurrentConfig,saveConfig:saveConfig,clearConfig:clearConfig,validate:validate,maskKey:maskKey,setConnection:setConnection,isConfigured:function(){return validate(getCurrentConfig()).valid;},_test:{configValue:configValue,signature:signature,loadStore:loadStore}};
  function providerError(code,msg,status){var e=new Error(msg);e.code=code;if(status)e.status=status;return e;} function endpoint(base){base=clean(base).replace(/\/+$/,'');return /\/chat\/completions$/i.test(base)?base:base+'/chat/completions';}
  function safeJson(text){text=clean(text).replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(text);}catch(e){var s=text.indexOf('{'),n=text.lastIndexOf('}');if(s>=0&&n>s)return JSON.parse(text.slice(s,n+1));throw providerError('INVALID_RESPONSE','模型返回格式不正确。');}}
  function mapFailure(s){if(s===401||s===403)return providerError('AUTH_FAILED','API Key 无效。',s);if(s===404)return providerError('MODEL_NOT_FOUND','模型不存在或接口地址错误。',s);if(s===402)return providerError('QUOTA_EXCEEDED','余额或额度不足。',s);if(s===429)return providerError('RATE_LIMITED','请求过于频繁或额度不足。',s);return providerError('PROVIDER_REQUEST_FAILED','模型服务请求失败（HTTP '+s+'）。',s);}
  function durationRange(d){d=Number(d||60);return d<=30?[70,110]:(d<=60?[120,190]:[190,290]);} function instructions(a,p){var common='你是短视频内容策略助手。只能根据输入中的真实字段工作，不得虚构事实。只返回严格 JSON，不要 Markdown。';if(a==='analyzeContent')return common+' 返回 topic,hook,angle,keyPoints(string[]),structure,interactionReasons(string[]),reusablePattern,limitations。'+(p.contentAvailable?'可以结合正文分析。':'limitations 必须说明当前仅基于标题和互动数据分析。');var rewrite=p.action&&p.action!=='generate',range=durationRange(p.duration),rules={'new-opening':'只替换开场钩子。',colloquial:'改成更自然的口语表达。',professional:'改成更专业克制的表达。',shorter:'body 不超过当前版本的 70%。','different-angle':'换一个不同的原创切入角度。'};return common+(rewrite?'返回 {"variants":[一个版本]}。'+(rules[p.action]||''):'生成三个不同原创版本，返回 {"variants":[三个版本]}。')+' 每个版本包含 angle,title,coverTitle,hook,body,cta,tags,estimatedDuration。'+(p.action==='shorter'?'':('body 目标 '+range[0]+'-'+range[1]+' 个中文字符。'));}
  var controllers=[];function fetchJson(url,o,t){var c=new AbortController(),timer=setTimeout(function(){c.abort();},t||TIMEOUT_MS);controllers.push(c);o.signal=c.signal;return fetch(url,o).then(function(r){if(!r.ok)throw mapFailure(r.status);return r.json();}).catch(function(e){if(e&&e.name==='AbortError')throw providerError('TIMEOUT','连接超时。');if(e&&e.code)throw e;throw providerError('NETWORK_ERROR','网络异常。该 Provider 可能不支持浏览器直连，需要代理模式。');}).finally(function(){clearTimeout(timer);var i=controllers.indexOf(c);if(i>=0)controllers.splice(i,1);});}
  function openAI(c,system,user,test){return fetchJson(endpoint(c.baseUrl),{method:'POST',headers:{Authorization:'Bearer '+c.apiKey,'Content-Type':'application/json'},body:JSON.stringify({model:c.model,messages:test?[{role:'user',content:'Reply with OK.'}]:[{role:'system',content:system},{role:'user',content:user}],temperature:test?0:0.5,max_tokens:test?8:undefined})},test?15000:TIMEOUT_MS).then(function(b){return b&&b.choices&&b.choices[0]&&b.choices[0].message&&b.choices[0].message.content;});}
  function anthropic(c,system,user,test){return fetchJson(c.baseUrl.replace(/\/$/,'')+'/messages',{method:'POST',headers:{'x-api-key':c.apiKey,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true','Content-Type':'application/json'},body:JSON.stringify({model:c.model,max_tokens:test?8:4096,system:test?'':system,messages:[{role:'user',content:test?'Reply with OK.':user}]})},test?15000:TIMEOUT_MS).then(function(b){return b&&b.content&&b.content[0]&&b.content[0].text;});}
  function gemini(c,system,user,test){return fetchJson(c.baseUrl.replace(/\/$/,'')+'/models/'+encodeURIComponent(c.model)+':generateContent',{method:'POST',headers:{'x-goog-api-key':c.apiKey,'Content-Type':'application/json'},body:JSON.stringify({systemInstruction:test?undefined:{parts:[{text:system}]},contents:[{role:'user',parts:[{text:test?'Reply with OK.':user}]}],generationConfig:{temperature:test?0:0.5,maxOutputTokens:test?8:4096}})},test?15000:TIMEOUT_MS).then(function(b){return b&&b.candidates&&b.candidates[0]&&b.candidates[0].content&&b.candidates[0].content.parts&&b.candidates[0].content.parts[0]&&b.candidates[0].content.parts[0].text;});}
  function call(c,system,user,test){var p=PRESETS[c.providerId];if(!p||p.supportsDirectBrowser===false)return Promise.reject(providerError('DIRECT_UNSUPPORTED','该 Provider 不支持浏览器直连，需要代理模式。'));var start=Date.now(),promise=p.adapter==='anthropic'?anthropic(c,system,user,test):(p.adapter==='gemini'?gemini(c,system,user,test):openAI(c,system,user,test));return promise.then(function(content){if(typeof content!=='string')throw providerError('INVALID_RESPONSE','模型返回内容为空。');return {content:content,latency:Date.now()-start,provider:c.providerId,model:c.model};});}
  function invoke(a,payload){var x=validate(getCurrentConfig());if(!x.valid)return Promise.reject(providerError('PROVIDER_NOT_CONFIGURED','请先配置文字模型 API。'));return call(x.config,instructions(a,payload),JSON.stringify(payload),false).then(function(r){var data=safeJson(r.content);if(data&&Array.isArray(data.variants))data.variants=data.variants.map(function(x){if(Array.isArray(x.tags))x.tags=x.tags.join(' ');if(x.estimatedDuration!=null)x.estimatedDuration=String(x.estimatedDuration);return x;});return {data:data,meta:r};});}
  window.TextAIProviderAdapter={testConnection:function(c){var x=validate(c);if(!x.valid)return Promise.reject(providerError('PROVIDER_NOT_CONFIGURED','请完整填写配置。'));return call(x.config,'','',true).then(function(r){return {ok:true,provider:r.provider,model:r.model,latency:r.latency};});},analyzeContent:function(c,w){return invoke('analyzeContent',w);},generateScript:function(c,o){return invoke('generateScript',o);},rewriteScript:function(c,o){return invoke('generateScript',Object.assign({},o,{action:o.action||'rewrite'}));},request:invoke,abortAll:function(){controllers.splice(0).forEach(function(c){try{c.abort();}catch(e){}});},_test:{endpoint:endpoint,safeJson:safeJson,instructions:instructions,mapFailure:mapFailure}};
})();
