/* ===== modules/techradar.js ===== */
(function(){
  'use strict';
  var loadVersion=0;
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
  function empty(title,text){return '<div class="empty-state"><strong>'+esc(title)+'</strong><br>'+esc(text)+'</div>';}
  function currentId(){var ctx=IndustryStore.getCurrent();return ctx&&ctx.id;}
  function repoBase(item,badge){var tags=(item.topics||[]).slice(0,4).map(function(tag){return '<span class="match-kw">'+esc(tag)+'</span>';}).join('');return '<article class="tech-card"><div class="tech-source">GitHub</div><div class="tech-header"><div class="tech-name">'+esc(item.name)+'</div>'+badge+'</div><div class="tech-desc">'+esc(item.descriptionZh||item.description||'暂无项目描述')+'</div><div class="tech-meta"><span>总 Stars '+item.stars.toLocaleString()+'</span><span>Forks '+item.forks.toLocaleString()+'</span><span>'+esc(item.language||'语言未知')+'</span><span>更新 '+esc(item.updatedAt.slice(0,10))+'</span></div>'+(tags?'<div class="tech-match">'+tags+'</div>':'')+'<a class="work-link" target="_blank" rel="noopener" href="'+esc(item.url)+'">查看 GitHub</a></article>';}
  function weeklyCard(item){var rate=item.growthRate7d==null?'':(' · '+(item.growthRate7d*100).toFixed(1)+'%');return repoBase(item,'<span class="tech-badge rise">+'+item.starsGained7d.toLocaleString()+' Stars / 7d'+rate+'</span>');}
  function emergingCard(item){return repoBase(item,'<span class="tech-badge blue">上线 '+item.ageDays+' 天 · 当前 '+item.stars.toLocaleString()+' Stars</span>');}
  function accumulatingCard(item){return repoBase(item,'<span class="tech-badge watch">近 7 天活跃 · 当前 '+item.stars.toLocaleString()+' Stars</span>');}
  function socialCard(item){var sample=item.sampleWorks>0?'<span>样本作品 '+item.sampleWorks.toLocaleString()+'</span>':'<span>当前样本 暂无采集作品</span>',delta=item.sampleWorksDelta==null?'':('<div class="tech-summary-note">样本作品变化 '+(item.sampleWorksDelta>=0?'+':'')+item.sampleWorksDelta.toLocaleString()+(item.engagementDeltaRate==null?'':' · 互动变化 '+(item.engagementDeltaRate*100).toFixed(1)+'%')+'</div>');return '<article class="tech-card"><div class="tech-source">RedFox 快照</div><div class="tech-header"><div class="tech-name">'+esc(item.name)+'</div><span class="tech-badge watch">'+esc(item.trend)+'</span></div><div class="tech-meta">'+sample+'<span>点赞 '+item.likes.toLocaleString()+'</span><span>收藏 '+item.collects.toLocaleString()+'</span><span>评论 '+item.comments.toLocaleString()+'</span><span>分享 '+item.shares.toLocaleString()+'</span></div>'+delta+'</article>';}
  function githubGroup(result){var weekly=result.weekly||[],emerging=result.emerging||[],accumulating=result.accumulating||[],weeklyHtml=weekly.length?weekly.map(weeklyCard).join(''):empty('历史数据积累中','持续采集 7 天后将显示真实周增长排名。'),emergingHtml=emerging.length?emerging.map(emergingCard).join(''):empty('暂无新兴项目','最近 7 天未发现符合当前 Radar Profile 的新仓库。'),accumulatingHtml=accumulating.length?accumulating.map(accumulatingCard).join(''):empty('暂无匹配项目','GitHub 当前未返回符合行业画像的活跃仓库。');return '<div class="radar-group"><div class="card-head"><span class="ch-bar"></span><span class="ch-title">GitHub 精准 Skill / 项目</span></div><div class="tech-summary-note">按当前行业画像检索近期活跃仓库；展示真实项目简介，周增长待快照积累后补充。</div><div class="tech-grid">'+accumulatingHtml+'</div></div><div class="radar-group"><div class="card-head"><span class="ch-bar"></span><span class="ch-title">本周 Star 增长最快</span></div><div class="tech-summary-note">'+esc(result.note)+'</div><div class="tech-grid">'+weeklyHtml+'</div></div><div class="radar-group"><div class="card-head"><span class="ch-bar"></span><span class="ch-title">新兴项目</span></div><div class="tech-summary-note">最近 7 天创建；展示当前 Stars 和上线天数，不标记为七天增长。</div><div class="tech-grid">'+emergingHtml+'</div></div>';}
  function standardGroup(result){return '<div class="radar-group"><div class="card-head"><span class="ch-bar"></span><span class="ch-title">'+esc(result.title)+'</span></div><div class="tech-summary-note">'+esc(result.note)+'</div><div class="tech-grid">'+(result.items.length?result.items.map(socialCard).join(''):empty('暂无数据','当前数据源暂未返回有效信号。'))+'</div></div>';}
  function renderResult(profile,results){var title=document.querySelector('[data-section="techradar"]'),summary=document.getElementById('techSummary'),grid=document.getElementById('techGrid'),total=results.reduce(function(sum,result){return sum+result.items.length;},0);if(title)title.textContent=profile.sources.github.enabled?'技术雷达':'行业雷达';if(!grid||!summary)return;summary.innerHTML='<div class="tech-summary-card"><div class="num">'+total+'</div><div class="label">当前真实信号</div></div><div class="tech-summary-card"><div class="label">GitHub 精准项目优先；行业热词作为辅助信号。</div></div>';if(!results.length){grid.innerHTML=empty('当前行业暂未形成足够趋势数据。','继续采集后，将根据 7 天变化自动生成雷达。');return;}results=results.slice().sort(function(a,b){return (a.kind==='github'?0:1)-(b.kind==='github'?0:1);});grid.innerHTML=results.map(function(result){return result.kind==='github'?githubGroup(result):standardGroup(result);}).join('');}
  function renderTechRadar(data){var profile=RadarProfileService.getCurrent(),grid=document.getElementById('techGrid'),summary=document.getElementById('techSummary'),version=++loadVersion,industryId=currentId(),jobs=[];if(profile.sources.social.enabled)jobs.push(RadarAdapters.social.load(profile,data||window.DASHBOARD_DATA||{}));if(profile.sources.github.enabled)jobs.push(RadarAdapters.github.load(profile));if(summary)summary.innerHTML='';if(grid)grid.innerHTML=empty('雷达数据加载中...','正在读取当前行业的数据源。');Promise.all(jobs).then(function(results){if(version!==loadVersion||industryId!==currentId())return;renderResult(profile,results);}).catch(function(error){if(version!==loadVersion||industryId!==currentId()||!grid)return;grid.innerHTML=empty('模块加载失败，请重试',error&&error.message?error.message:'雷达数据暂时不可用。');});}
  if(window.Module)Module.register({id:'techradar',render:function(data){renderTechRadar(data);}});
  window.renderTechRadar=renderTechRadar;
})();
