/* ===== modules/textAISettings.js ===== */
(function(){
  'use strict';
  var lastConnection=null;
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function field(id){var e=document.getElementById(id);return e?String(e.value||'').trim():'';}
  function currentForm(){var id=field('textAIProvider'),saved=TextAIProvider.getConfig(id),preset=TEXT_PROVIDER_PRESETS[id],manual=document.getElementById('textAIManualModelWrap');return {providerId:id,providerType:preset.adapter,baseUrl:preset.showBaseUrl?field('textAIBaseUrl'):preset.baseUrl,apiKey:field('textAIKey')||(saved&&saved.apiKey)||'',model:manual&&manual.hidden?field('textAIModelSelect'):field('textAIModelManual')};}
  function statusHtml(c){if(!c)return '<div class="text-ai-status is-empty"><strong>尚未配置文字模型</strong><span>配置后即可使用 AI 内容拆解、口播生成和快捷改写。</span></div>';var x=c.connection||{},label=x.status==='success'?'已连接':(x.status==='failed'?'连接失败':'未测试'),tone=x.status==='success'?'is-success':(x.status==='failed'?'is-error':'is-pending');return '<div class="text-ai-status '+tone+'"><strong>'+esc(TEXT_PROVIDER_PRESETS[c.providerId].name)+' · '+esc(c.model)+'</strong><span>'+label+' · Key：'+esc(TextAIProvider.maskKey(c.apiKey))+'</span></div>';}
  function providerOptions(id){return Object.keys(TEXT_PROVIDER_PRESETS).map(function(key){var p=TEXT_PROVIDER_PRESETS[key];return '<option value="'+key+'"'+(key===id?' selected':'')+'>'+esc(p.name)+'</option>';}).join('');}
  function modelOptions(p,model){var models=(p.recommendedModels||[]).slice();if(model&&models.indexOf(model)<0)models.push(model);return models.map(function(x){return '<option value="'+esc(x)+'"'+(x===model?' selected':'')+'>'+esc(x)+'</option>';}).join('')+'<option value="__manual__">手动输入模型 ID</option>';}
  function render(){var host=document.getElementById('textAISettings');if(!host)return;var id=TextAIProvider.getCurrentProviderId(),p=TEXT_PROVIDER_PRESETS[id]||TEXT_PROVIDER_PRESETS.openai,c=TextAIProvider.getConfig(id),model=c&&c.model||p.recommendedModels[0]||'',manual=!(p.recommendedModels||[]).length||!!model&&(p.recommendedModels||[]).indexOf(model)<0;
    host.innerHTML='<div class="text-ai-heading"><div><h3>文字模型 API</h3><p>选择服务商，填写 API Key，即可使用 AI 功能。</p></div><span class="text-ai-mode">浏览器直连</span></div>'+statusHtml(c)+'<div class="text-ai-form">'+
      '<label>Provider<select id="textAIProvider" class="industry-flow-input">'+providerOptions(id)+'</select></label>'+
      '<label>API Key<div class="text-ai-key-row"><input id="textAIKey" class="industry-flow-input" type="password" autocomplete="new-password" placeholder="'+esc(c?TextAIProvider.maskKey(c.apiKey):'输入 API Key')+'"><button type="button" data-text-ai-action="toggle-key" aria-label="显示 API Key">显示</button></div></label>'+
      '<label>'+(p.modelLabel||'Model')+'<select id="textAIModelSelect" class="industry-flow-input">'+modelOptions(p,model)+'</select></label>'+
      '<label id="textAIManualModelWrap"'+(manual?'':' hidden')+'>手动输入模型 ID<input id="textAIModelManual" class="industry-flow-input" type="text" value="'+esc(manual?model:'')+'" placeholder="model id"></label>'+
      '<label id="textAIBaseUrlWrap"'+(p.showBaseUrl?'':' hidden')+'>API Base URL<input id="textAIBaseUrl" class="industry-flow-input" type="url" value="'+esc(c&&c.baseUrl||p.baseUrl||'')+'" placeholder="https://provider.example/v1"></label>'+
      '<div class="text-ai-result" id="textAIResult" aria-live="polite"></div><div class="text-ai-actions"><button type="button" data-text-ai-action="test">测试连接</button><button type="button" class="v82-primary" data-text-ai-action="save">保存配置</button><button type="button" class="is-danger" data-text-ai-action="clear">清除当前配置</button></div></div>'+
      '<p class="text-ai-security">API Key 仅保存在当前浏览器。请勿在公共电脑保存长期有效的 API Key。</p><details class="text-ai-guide"><summary>如何获取 API Key？</summary><ol><li>注册 '+esc(p.name)+'</li><li>创建并复制 API Key</li><li>返回本页填写</li><li>选择模型并测试连接</li></ol>'+(p.apiKeyGuideUrl?'<a href="'+esc(p.apiKeyGuideUrl)+'" target="_blank" rel="noopener noreferrer">打开官方 API Key 页面</a>':'')+'</details>';
    if(manual)document.getElementById('textAIModelSelect').value='__manual__';
  }
  function result(msg,type){var h=document.getElementById('textAIResult');if(h){h.className='text-ai-result '+(type||'');h.textContent=msg;}}
  function switchProvider(id){TextAIProvider.selectProvider(id);lastConnection=null;render();}
  function test(){var c=currentForm(),x=TextAIProvider.validate(c);if(!x.valid){result('请填写：'+x.missing.join('、'),'is-error');return;}result('正在测试最小文本请求…','is-pending');TextAIProviderAdapter.testConnection(c).then(function(v){lastConnection={status:'success',provider:v.provider,model:v.model,latency:v.latency};result('连接成功 · '+TEXT_PROVIDER_PRESETS[v.provider].name+' · '+v.model+' · '+v.latency+'ms','is-success');}).catch(function(e){lastConnection={status:'failed',code:e&&e.code||'UNKNOWN'};result(e&&e.message||'连接失败。','is-error');});}
  function save(){var x=TextAIProvider.saveConfig(currentForm());if(!x.valid){result('请填写：'+x.missing.join('、'),'is-error');return;}if(lastConnection)TextAIProvider.setConnection(lastConnection);render();result('配置已保存。','is-success');}
  function clear(){TextAIProvider.clearConfig();lastConnection=null;render();result('当前 Provider 配置已清除。','is-success');}
  document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-text-ai-action]');if(!b)return;var a=b.getAttribute('data-text-ai-action');if(a==='toggle-key'){var i=document.getElementById('textAIKey');i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'显示':'隐藏';}else if(a==='test')test();else if(a==='save')save();else if(a==='clear')clear();});
  document.addEventListener('change',function(e){if(e.target.id==='textAIProvider')switchProvider(e.target.value);if(e.target.id==='textAIModelSelect'){var wrap=document.getElementById('textAIManualModelWrap');wrap.hidden=e.target.value!=='__manual__';if(!wrap.hidden)document.getElementById('textAIModelManual').focus();}});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();window.TextAISettings={render:render};
})();
